### ISSUE TITLE
When parse the xml , it will auto change the String of contains ' &lt; '  to ' < ' ,I don't  want to do that.

### ISSUE THREAD

**Issue by SunLongbri** [renggli/dart-xml#67]
data:   "Material_Describe":"不锈钢管 BPE 1” PE   &lt;0.2umMP+EP A270 TP316L"
result: ""Material_Describe":"不锈钢管 BPE 1” PE   <0.2umMP+EP A270 TP316L""

**Comment by SunLongbri** [comment]
data :"Material_Describe":"不锈钢管 BPE 1” PE   &lt;0.2umMP+EP A270 TP316L"

**Comment by SunLongbri** [comment]
the data :PE <0.2umMP  is  "PE '&lt;'0.2umMP"

**Comment by renggli** [comment]
With version [https://pub.dev/packages/xml#360](3.6.0) all parts of `xml` support custom entity mapping. Create your own instance or implementation of [XmlDefaultEntityMapping ](https://github.com/renggli/dart-xml/blob/91749867cb5cfd4c446a4f0aaa64dbb29d0d8340/lib/src/xml/entities/default_mapping.dart) to customize the decoding in `String decodeEntity(String)`.

**Comment by SunLongbri** [comment]
Ok Thanks

**Comment by renggli** [comment]
I've pushed version 3.6.1 that includes https://github.com/renggli/dart-xml/blob/master/lib/src/xml/entities/null_mapping.dart.

**Comment by ali-thowfeek** [comment]
Hi, @renggli I know this is closed, but I still cant get my head around this.

Im using your package in [simple_html_css](https://github.com/ali-thowfeek/simple_html_css_flutter) package.
Where the parse method is used, ` _events = parseEvents("<p>html content here</p>");` like so.

Im getting a XmlParserException when there's a `<` in the string within tags, like:
`_events = parseEvents("<p>Number 10 < 20</p>");`

I tried the following with no avail:
`_events = parseEvents(data, entityMapping: const XmlDefaultEntityMapping.html5());`

Maybe Im using `XmlDefaultEntityMapping` very wrong. Any help would be much appreciated.

**Comment by renggli** [comment]
The problem is that your input is not valid XML. The entity mapping only defines how entities such as `&nbsp;` are mapped to a specific character and back. In this context, the `<` character is always read as the beginning of an opening tag. Your input needs to either encode such characters `"<p>Number 10 &lt; 20</p>"` or wrap the string in a CDATA section `"<p><![CDATA[Number 10 < 20]]></p>"` to get a readable XML input.

Note that XML and HTML are very different, despite their similar look: XML is strict, it requires all tags to be closed, it is case-sensitive, it doesn't silently skip over invalid nesting or other errors, etc.

That said, with the event based parsing you can deal with invalid input: the [test here](https://github.com/renggli/dart-xml/blob/a8c5813c11c681b92f993abb1d16cd2e86bed8ec/test/events_test.dart#L182) resumes the iteration with the next character after the `XmlParserException` was thrown.
